CREATE INDEX IX1_LOCATIONS ON LOCATIONS(UPPER("LOCATIONNAME"));
CREATE INDEX IX2_LOCATIONS ON LOCATIONS(UPPER("LOCATIONNAME"), POPULATION);
CREATE INDEX IX3_LOCATIONS ON LOCATIONS(UPPER("LOCATIONNAME"), UPPER("ADMIN1"), POPULATION);
CREATE INDEX IX4_LOCATIONS ON LOCATIONS(UPPER("LOCATIONNAME"), UPPER("ADMIN1LONG"));
CREATE INDEX IX5_LOCATIONS ON LOCATIONS(UPPER("ADMIN1"));
