update locations set admin1long = 'Alabama' where admin1='AL';
update locations set admin1long = 'Alaska' where admin1='AK';
update locations set admin1long = 'Arizona' where admin1='AZ';
update locations set admin1long = 'Arkansas' where admin1='AR';
update locations set admin1long = 'California' where admin1='CA';
update locations set admin1long = 'Colorado' where admin1='CO';
update locations set admin1long = 'Connecticut' where admin1='CT';
update locations set admin1long = 'Delaware' where admin1='DE';
update locations set admin1long = 'District of Columbia' where admin1='DC';
update locations set admin1long = 'Florida' where admin1='FL';
update locations set admin1long = 'Georgia' where admin1='GA';
update locations set admin1long = 'Hawaii' where admin1='HI';
update locations set admin1long = 'Idaho' where admin1='ID';
update locations set admin1long = 'Illinois' where admin1='IL';
update locations set admin1long = 'Indiana' where admin1='IN';
update locations set admin1long = 'Iowa' where admin1='IA';
update locations set admin1long = 'Kansas' where admin1='KS';
update locations set admin1long = 'Kentucky' where admin1='KY';
update locations set admin1long = 'Louisiana' where admin1='LA';
update locations set admin1long = 'Maine' where admin1='ME';
update locations set admin1long = 'Montana' where admin1='MT';
update locations set admin1long = 'Nebraska' where admin1='NE';
update locations set admin1long = 'Nevada' where admin1='NV';
update locations set admin1long = 'New Hampshire' where admin1='NH';
update locations set admin1long = 'New Jersey' where admin1='NJ';
update locations set admin1long = 'New Mexico' where admin1='NM';
update locations set admin1long = 'New York' where admin1='NY';
update locations set admin1long = 'North Carolina' where admin1='NC';
update locations set admin1long = 'North Dakota' where admin1='ND';
update locations set admin1long = 'Ohio' where admin1='OH';
update locations set admin1long = 'Oklahoma' where admin1='OK';
update locations set admin1long = 'Oregon' where admin1='OR';
update locations set admin1long = 'Maryland' where admin1='MD';
update locations set admin1long = 'Massachusetts' where admin1='MA';
update locations set admin1long = 'Michigan' where admin1='MI';
update locations set admin1long = 'Minnesota' where admin1='MN';
update locations set admin1long = 'Mississippi' where admin1='MS';
update locations set admin1long = 'Missouri' where admin1='MO';
update locations set admin1long = 'Pennsylvania' where admin1='PA';
update locations set admin1long = 'Rhode Island' where admin1='RI';
update locations set admin1long = 'South Carolina' where admin1='SC';
update locations set admin1long = 'South Dakota' where admin1='SD';
update locations set admin1long = 'Tennessee' where admin1='TN';
update locations set admin1long = 'Texas' where admin1='TX';
update locations set admin1long = 'Utah' where admin1='UT';
update locations set admin1long = 'Vermont' where admin1='VT';
update locations set admin1long = 'Virginia' where admin1='VA';
update locations set admin1long = 'Washington' where admin1='WA';
update locations set admin1long = 'West Virginia' where admin1='WV';
update locations set admin1long = 'Wisconsin' where admin1='WI';
update locations set admin1long = 'Wyoming' where admin1='WY'
commit;
